### ISSUE TITLE
Please use the iam roles attached to the machine

### ISSUE THREAD

**Issue by runningman84** [janbuecker/SwagMediaS3#1]
Today it is recommended not to save AWS secrets on a machine. These credentials should be provided by an iam role:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html

Is the secret and key mandatory?

**Comment by janbuecker** [comment]
hi, this repository has moved into the shopwareLabs. I've created a new issue there.

https://github.com/shopwareLabs/SwagMediaS3/issues/1
